import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    rootContainer: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    mainContainer: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    overlay: {
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
    },
    sidebar: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        width: 280,
        backgroundColor: '#FFFFFF',
        zIndex: 1000,
        elevation: 16,
        shadowColor: '#000000',
        shadowOffset: { width: -2, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
    },
    sidebarHeader: {
        paddingTop: 60,
        paddingHorizontal: 24,
        paddingBottom: 24,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    sidebarUserInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sidebarAvatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#5B67CA',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    sidebarAvatarText: {
        fontSize: 20,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    sidebarUserName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2B2B2B',
        marginBottom: 4,
    },
    sidebarUserEmail: {
        fontSize: 14,
        color: '#666666',
    },
    sidebarGuestText: {
        fontSize: 16,
        color: '#666666',
    },
    sidebarMenu: {
        paddingTop: 16,
    },
    sidebarMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 24,
    },
    sidebarMenuIcon: {
        fontSize: 20,
        marginRight: 16,
        width: 24,
        textAlign: 'center',
    },
    sidebarMenuText: {
        fontSize: 16,
        color: '#2B2B2B',
    },
    sidebarLogoutText: {
        color: '#E74C3C',
    },
    loginButton: {
        backgroundColor: '#5B67CA',
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 24,
        marginTop: 12,
    },
    loginButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    loginBottomButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 24,
        marginTop: 8,
    },
    loginBottomIcon: {
        fontSize: 18,
        marginRight: 12,
    },
    loginBottomText: {
        fontSize: 15,
        color: '#2B2B2B',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    aiPlannerHeaderButton: {
        backgroundColor: '#9B59B6',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginRight: 12,
    },
    aiPlannerHeaderText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '600',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerLogo: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#5B67CA',
        letterSpacing: 2,
    },
    headerIcon: {
        padding: 8,
    },
    headerIconText: {
        fontSize: 22,
    },
    searchContainer: {
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 8,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
    },
    searchIcon: {
        fontSize: 20,
        color: '#999999',
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#2B2B2B',
    },
    clearButton: {
        fontSize: 18,
        color: '#999999',
        paddingHorizontal: 8,
    },
    scrollView: {
        flex: 1,
    },
    categoryScrollView: {
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    categoryContent: {
        paddingHorizontal: 16,
    },
    categoryItem: {
        alignItems: 'center',
        marginRight: 20,
    },
    categoryIconCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#F5F5F5',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 6,
    },
    aiPlannerIconCircle: {
        backgroundColor: '#E8D5F2',
    },
    categoryEmoji: {
        fontSize: 24,
    },
    categoryLabel: {
        fontSize: 12,
        color: '#666666',
        fontWeight: '500',
    },
    greetingSection: {
        paddingHorizontal: 16,
        paddingVertical: 20,
    },
    greetingText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2B2B2B',
        marginBottom: 8,
    },
    userNameHighlight: {
        color: '#5B67CA',
    },
    greetingSubtext: {
        fontSize: 16,
        color: '#666666',
    },
    reviewGridContainer: {
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    reviewRow: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    reviewCard: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
        marginHorizontal: 6,
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    reviewImage: {
        width: '100%',
        height: 100,
        borderRadius: 8,
        marginBottom: 8,
        backgroundColor: '#F5F5F5',
    },
    reviewTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2B2B2B',
        marginBottom: 4,
    },
    reviewAuthor: {
        fontSize: 12,
        color: '#888888',
    },
    aiPlannerCTA: {
        marginHorizontal: 16,
        marginBottom: 20,
        backgroundColor: '#9B59B6',
        borderRadius: 16,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        elevation: 4,
        shadowColor: '#9B59B6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    aiPlannerCTAContent: {
        flex: 1,
    },
    aiPlannerCTATitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    aiPlannerCTASubtitle: {
        fontSize: 14,
        color: '#FFFFFF',
        opacity: 0.9,
    },
    aiPlannerCTAArrow: {
        fontSize: 24,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    cardsContainer: {
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    travelCard: {
        marginBottom: 16,
        borderRadius: 16,
        overflow: 'hidden',
        backgroundColor: '#FFFFFF',
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardImage: {
        width: '100%',
        height: 200,
    },
    cardOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'flex-end',
        padding: 16,
    },
    authorBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    authorText: {
        fontSize: 12,
        color: '#2B2B2B',
        fontWeight: '600',
    },
    listBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    listBadgeText: {
        fontSize: 12,
        color: '#2B2B2B',
        fontWeight: '600',
    },
    cardContent: {
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        padding: 12,
        borderRadius: 8,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    cardLocation: {
        fontSize: 14,
        color: '#FFFFFF',
    },
    promoBanner: {
        flexDirection: 'row',
        backgroundColor: '#FFF9E6',
        marginHorizontal: 16,
        marginBottom: 20,
        padding: 20,
        borderRadius: 16,
        alignItems: 'center',
    },
    promoContent: {
        flex: 1,
    },
    promoTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#2B2B2B',
        marginBottom: 4,
    },
    promoSubtitle: {
        fontSize: 14,
        color: '#666666',
    },
    promoImageContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#FFE5B4',
        justifyContent: 'center',
        alignItems: 'center',
    },
    promoEmoji: {
        fontSize: 32,
    },
    actionButtonsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    planButton: {
        flex: 1,
        backgroundColor: '#5B67CA',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        marginRight: 8,
    },
    planButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    mapButton: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#5B67CA',
        shadowColor: '#5B67CA',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    mapButtonText: {
        color: '#000000',
        fontSize: 16,
        fontWeight: '600',
    },
    recommendSection: {
        paddingTop: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2B2B2B',
        paddingHorizontal: 16,
        marginBottom: 16,
    },
    citiesContainer: {
        paddingHorizontal: 16,
    },
    cityCard: {
        marginRight: 12,
        alignItems: 'center',
    },
    cityImage: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 8,
        backgroundColor: '#E0E0E0',
    },
    cityName: {
        fontSize: 13,
        color: '#333333',
        fontWeight: '500',
    },
    aiPlannerButton: {
        flex: 1,
        backgroundColor: '#9B59B6',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        marginLeft: 8,
    },
    aiPlannerButtonText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    logo: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#5B67CA',
    },
    profileSection: {
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    avatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#5B67CA',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    avatarText: {
        fontSize: 24,
        color: '#FFFFFF',
        fontWeight: 'bold',
    },
    userEmail: {
        fontSize: 14,
        color: '#666666',
        marginTop: 4,
    },
    divider: {
        height: 1,
        backgroundColor: '#E0E0E0',
        marginVertical: 8,
    },
    menuContainer: {
        paddingVertical: 8,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    menuIcon: {
        fontSize: 20,
        marginRight: 16,
        width: 24,
    },
    menuLabel: {
        fontSize: 16,
        color: '#2B2B2B',
    },
    bottomSection: {
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
    },
    sidebarActionButton: {
        backgroundColor: '#5B67CA',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
    },
    sidebarActionButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});

export const CARD_WIDTH = 280;
export const SIDEBAR_WIDTH = 280;

export default styles;
